name: some-tank-game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set current date as env variable
      run: echo "NOW=$(Get-Date -Format 'yyyy-MM-dd')" >> $env:GITHUB_ENV
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      run: ./release.bat
    - name: Archive non-installer release
      uses: actions/upload-artifact@v2
      with:
        name: ${{env:GITHUB_WORKFLOW}}-${{env:GITHUB_SHA}}-${{env.NOW}}
        path: |
          dist
    - name: Archive installer release
      uses: actions/upload-artifact@v2
      with:
        name: ${{env:GITHUB_WORKFLOW}}-installer-${{env:GITHUB_SHA}}-${{env.NOW}}
        path: SomeTankGame.exe